### ISSUE TITLE
Bot can be used to ping people

### ISSUE THREAD

**Issue by ChaiTRex** [rust-community-discord/ferrisbot-for-discord#26]
See https://discord.com/channels/273534239310479360/273541645579059201/1206323374184337438

Typing:
```
?crate ``a```<@259840591393718274>```a``
```
Produces:
![Untitled](https://github.com/rust-community-discord/ferrisbot-for-discord/assets/23159282/0ddcb4a9-507b-4fb5-96e7-6cdfbda2c3b1)

**Comment by wackbyte** [comment]
wow! i'm famous!
