### ISSUE TITLE
Main fn wrapping completely breaks formatting

### ISSUE THREAD

**Issue by Noratrieb** [rust-community-discord/ferrisbot-for-discord#29]
![Screenshot_20240511-093518](https://github.com/rust-community-discord/ferrisbot-for-discord/assets/48135649/876e102d-1099-4352-a456-cbce815ab07b)

this is a regression from #27 (cc @bend-n if you want to fix it, don't have to of course)

i think the wrapping should continue being string based to fully preserve formatting, but using syn to *detect* whether wrapping should be done sounds reasonable.

**Comment by bend-n** [comment]
so we have two options
find the span of where #! starts and match it to the code, OR
rustfmt

**Comment by Noratrieb** [comment]
I do not think ferris should touch the formatting of the supplied source code. it should just wrap it in the strings with format!() as it did before

**Comment by bend-n** [comment]
yeah but format is easier
