### ISSUE TITLE
Add way to change server logo over time

### ISSUE THREAD

**Issue by ivandardi** [rust-community-discord/ferrisbot-for-discord#7]
The RPLCS in Discord wants to be able to change the server icon over time.

I'd like to have the server icon be changed to the server icons available in the `assets` folder. I want the server icon to change every 24 hours at noon, UTC 0. The new server icon should be randomly chosen from any of the server icons available in the folder.

Possible implementations include:

1. Adding a tokio background task in the bot's `setup()` function, and then have it execute the business logic above.

2. Adding an `if` in the bot's `event_handler()` function and executing the business logic there.

**Comment by lilyyy411** [comment]
I remember implementing a similar system in my own bot and going with the first one. Green threads are cheap and a simple future like waiting a long time and then doing something should be cheap for the runtime and feels more idiomatic than using `if` statements in an event handler imo.

**Comment by anden3** [comment]
> I remember implementing a similar system in my own bot and going with the first one. Green threads are cheap and a simple future like waiting a long time and then doing something should be cheap for the runtime and feels more idiomatic than using `if` statements in an event handler imo.

Yeah, a tokio task iterating over an interval will have effectively zero overhead :)

**Comment by GnomedDev** [comment]
This has been implemented, right?

**Comment by ivandardi** [comment]
Yes! Closing now.
