### ISSUE TITLE
Make command that allows the creators of threads to pin messages in them.

### ISSUE THREAD

**Issue by ivandardi** [rust-community-discord/ferrisbot-for-discord#8]
Currently Discord doesn't allow me to allow thread creators to pin messages in them. That's a desired functionality.

Copy of the server-feedback discussion with names edited out

---

Several channels, including ⁠casual-chat, ⁠lang-dev, and ⁠dark-arts, have long running threads that act as standing specialized discussion channels. In some cases, it may be useful to have certain information pinned in the channel. I thus propose that thread owners should have the ability to pin messages in their threads, likely through a slash command or application command.

I thought this was already the case. Can you not pin your own message in this thread?

Nope.

Freaky

We need to figure out what permissions need to be fixed to do this, then

I don't think there's per-thread permissions for Manage Messages.
I was thinking make it a feature of @Ferris 🦀.
perhaps a context menu?

Yeah, an application command either way.

**Comment by ferris** [comment]
I have been summoned 🫥

**Comment by ivandardi** [comment]
Wrong ferris, sorry for the mention! Also, hi! 😀

**Comment by ferris** [comment]
No worries. I find it funny that the Rust mascot has the same name as me. Really ought to learn the language at some point. Good luck on this project it seems interesting!

**Comment by danielrab** [comment]
I am working on this. Shouldn't take too long.

**Comment by danielrab** [comment]
well, famous last words I guess. Can't figure out how to find who created the thread.

**Comment by ivandardi** [comment]
Is that not given by the API, or it is and it's just not being exposed through poise?

**Comment by wackbyte** [comment]
The user ID of the thread/forum post creator is available as the `owner_id` field on `GuildChannel`. This is only available in serenity 0.12, though, and poise requires 0.11.

**Comment by GnomedDev** [comment]
I'm working on this now.
