### ISSUE TITLE
Implement modmail report context-menu ricght-click action

### ISSUE THREAD

**Issue by ivandardi** [rust-community-discord/ferrisbot-for-discord#9]
Currently we have a modmail system. We'd like to expand that by allowing people to report messages directly to a Modmail by right clicking, then going to Apps, and then clicking "Send message to Modmail". 

Feedback copied from the server:

---

It'd be nice if there was a way to report messages from the right-click>apps menu, even though it's terribly named.

**Comment by GnomedDev** [comment]
![image](https://github.com/user-attachments/assets/83a3b31f-2ef5-47da-b290-345b1622a254)
Isn't this implemented?

**Comment by ivandardi** [comment]
Yes! Closing now.
